---
kind: pipeline
name: Install test and build
steps:
  - name: install
    image: node:10-alpine
    commands:
      - npm audit
      - npm ci
  - name: lint
    image: node:10-alpine
    commands:
      - npx commitlint --from develop --to $DRONE_COMMIT
      - npx stylelint './src/**/*.js'
      - npx eslint ./src
  - name: test
    image: node:10-alpine
    commands:
      - npx react-scripts test --coverage
  - name: build
    image: node:10-alpine
    commands:
      - npx react-scripts build
