---
kind: pipeline
name: Install test and build
steps:
  - name: install
    image: bycedric/ci-node
    commands:
      - npm audit
      - npm ci
  - name: lint
    image: bycedric/ci-node
    commands:
      - npx stylelint './src/**/*.js'
      - npx eslint ./src
  - name: test
    image: bycedric/ci-node
    commands:
      - npx react-scripts test --coverage
  - name: build
    image: bycedric/ci-node
    commands:
      - npx react-scripts build
