---
language: node_js
node_js:
  - node
  - lts/*

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npx commitlint-travis
  - npx stylelint ./src/**/*.js
  - npx eslint ./src
  - npx react-scripts test --coverage
  - npm run build

after_success:
  - npx codecov

deploy:
  - provider: script
    skip_cleanup: true
    script: >
      npx semantic-release --dry-run --branch develop &&
      npm run build &&
      npx now ./build -t $NOW_TOKEN -T personal -A ./now.staging.json &&
      npx now alias -A ./now.staging.json
    on:
      condition: $TRAVIS_OS_NAME = linux
      branch: develop
      node: lts/*
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      condition: $TRAVIS_OS_NAME = linux
      branch: master
      node: lts/*
