---
language: node_js
node_js:
  - node
  - lts/*

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npx commitlint-travis
  - npx stylelint ./src/**/*.js
  - npx eslint ./src
  - npx react-scripts test --coverage

after_success:
  - npx codecov

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release --dry-run --branch develop
    on:
      branch: develop
      node: lts/*
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      branch: master
      node: lts/*
