---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
install:
  - npm ci
script:
  - npx commitlint-travis
  - npx eslint ./src
  - npm test
after_success:
  - npx codecov
