---
language: node_js
node_js:
  - node
  - lts/*

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npx commitlint-travis
  - npx stylelint './src/**/*.js'
  - npx eslint ./src
  - npx react-scripts test --coverage
  - npm run build

after_success:
  - npx codecov

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      npx semantic-release --dry-run --branch develop &&
      npm run build &&
      cp now.staging.json now.json &&
      npx now deploy --token=$NOW_TOKEN --team=personal --name=bycedric-website-staging --regions=bru ./build &&
      npx now alias --token=$NOW_TOKEN --team=personal
    on:
      condition: $TRAVIS_OS_NAME = linux
      branch: develop
      node: lts/*
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      condition: $TRAVIS_OS_NAME = linux
      branch: master
      node: lts/*
