---
language: node_js
node_js:
  - 11
  - 10
  - 8
os:
  - linux
  - osx
cache: npm
script:
  - npx commitlint-travis
  - npx stylelint './src/**/*.js'
  - npx eslint ./src
  - npx react-scripts test --coverage
after_success:
  - npx codecov
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release --dry-run --branch develop
    on:
      node: 11
      branch: develop
      condition: $TRAVIS_OS_NAME = linux
