---
language: node_js
node_js:
  - node
os:
  - linux
  - osx
cache: npm
script:
  - npx commitlint-travis
  - npx stylelint './src/**/*.js'
  - npx eslint ./src
  - npx react-scripts test --coverage
after_success:
  - npx codecov
