---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
install:
  - npm ci
script:
  - npx commitlint-travis
  - npx eslint ./src
  - npx stylelint ./src/**/*.js
  - npm test -- --coverage
after_success:
  - npx codecov
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release --dry-run --branch develop
    on:
      branch: develop
      node: lts/*
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      branch: master
      node: lts/*
